# Generated by Django 5.2.4 on 2025-08-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='document',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
