# Generated by Django 5.2.4 on 2025-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block_Transaction',
            new_name='BlockTransaction',
        ),
        migrations.RenameField(
            model_name='blocktransaction',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='blocktransaction',
            old_name='voter_id',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='revote',
            old_name='voter_id',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='Signature',
            new_name='signature',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='voter_id',
            new_name='voter',
        ),
        migrations.AlterField(
            model_name='user',
            name='voter_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
