# Generated by Django 5.2.4 on 2025-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0002_rename_block_transaction_blocktransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
