# Generated by Django 5.2.4 on 2025-08-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0002_candidate_document_candidate_email_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='document',
            field=models.FileField(upload_to='candidates/'),
        ),
    ]
