# Generated by Django 5.2.4 on 2025-08-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0003_alter_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint',
            field=models.CharField(max_length=65, null=True, unique=True),
        ),
    ]
