# Generated by Django 5.2.4 on 2025-08-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0003_alter_candidate_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
