# Generated by Django 5.2.4 on 2025-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0004_user_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
