# Generated by Django 5.2.4 on 2025-08-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0005_candidate_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
