# Generated by Django 5.2.4 on 2025-08-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0006_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunabE.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunabE.election')),
            ],
        ),
    ]
