# Generated by Django 5.2.4 on 2025-08-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0007_electionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chunabE.election'),
            preserve_default=False,
        ),
    ]
