# Generated by Django 5.2.4 on 2025-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0012_alter_candidate_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='blocktransaction',
            name='voter',
        ),
        migrations.AddField(
            model_name='block',
            name='difficulty',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='block',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='index',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='block',
            name='merkle_root',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='encrypted_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='encrypted_vote',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='tx_hash',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='voter_hash',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='private_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='public_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='salt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'candidate', 'election')},
        ),
    ]
