# Generated by Django 5.2.4 on 2025-08-23 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0013_alter_block_options_remove_blocktransaction_voter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='blocktransaction',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='blocktransaction',
            name='encrypted_key',
        ),
        migrations.RemoveField(
            model_name='blocktransaction',
            name='encrypted_vote',
        ),
        migrations.RemoveField(
            model_name='blocktransaction',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='blocktransaction',
            name='voter_hash',
        ),
        migrations.RemoveField(
            model_name='revote',
            name='voter',
        ),
        migrations.AddField(
            model_name='blocktransaction',
            name='vote',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='chunabE.vote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='aes_key_wrapped',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate_ciphertext',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='credential_sig',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='serial_commitment',
            field=models.CharField(db_index=True, default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunabE.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_committed',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
    ]
