# Generated by Django 5.2.4 on 2025-08-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0015_votehistory_votercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
