# Generated by Django 5.2.4 on 2025-08-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0016_user_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votercredential',
            name='is_used',
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_credential',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chunabE.votercredential'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votercredential',
            name='serial_number_hash',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votercredential',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
