# Generated by Django 5.2.4 on 2025-08-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0017_remove_votercredential_is_used_vote_voter_credential_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votercredential',
            old_name='serial_number_hash',
            new_name='serial_number_b64',
        ),
    ]
