# Generated by Django 5.2.4 on 2025-08-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0018_rename_serial_number_hash_votercredential_serial_number_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter_credential',
        ),
        migrations.AddField(
            model_name='vote',
            name='tx_hash',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votercredential',
            name='serial_number_hash',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'serial_commitment'], name='chunabE_vot_electio_0b7b68_idx'),
        ),
        migrations.AddField(
            model_name='tally',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunabE.candidate'),
        ),
        migrations.AddField(
            model_name='tally',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunabE.election'),
        ),
    ]
