# Generated by Django 5.2.4 on 2025-08-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunabE', '0019_tally_remove_vote_voter_credential_vote_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
